name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Instalar Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install flake8 pytest coverage bandit

      - name: Lint (flake8)
        run: flake8 app

      - name: Análise de segurança (Bandit)
        run: bandit -r app

      - name: Testes com cobertura (pytest + coverage)
        run: |
          coverage run -m pytest
          coverage report
          coverage html  # Gera relatório em HTML (opcional)

  docker-cd:
    needs: build-test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build da imagem Docker
        run: docker build -t flask-devops-app .
