# ----------------------------------------------------------------
# .github/workflows/ci.yml
# Descrição: Pipeline de CI para Flask MoviesApp
# Executa lint + testes em Python 3.10 e 3.11
# ----------------------------------------------------------------

name: CI

# Gatilhos: sempre que houver push ou PR nas branches main ou develop
on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.10, 3.11]

    steps:
      # 1. Clonar repositório
      - name: Checkout do código
        uses: actions/checkout@v4

      # 2. Instalar versão do Python
      - name: Configurar Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      # 3. Instalar dependências
      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 4. Verificação de lint
      - name: Lint com flake8
        run: |
          pip install flake8
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics

      # 5. Executar testes
      - name: Executar testes com pytest
        run: |
          pip install pytest
          pytest --maxfail=1 --disable-warnings -q

      # 6. (Opcional) Relatório de cobertura
      - name: Relatório de coverage
        if: success()
        run: |
          pip install coverage
          coverage run -m pytest
          coverage report -m
